name: text_editor
description: Flutter quill sample.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.0+1

  #6.2.2 version is a version before flutter 3.3.7
  flutter_quill: 6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
